services:
  - type: web
    name: botesh-backend
    env: node
    rootDir: backend
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: BRAVE_SEARCH_API_KEY
        sync: false
      - key: BRAVE_AI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production 